
package WS;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.7-b01 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Dws", targetNamespace = "http://WebService/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Dws {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCurDate", targetNamespace = "http://WebService/", className = "WS.GetCurDate")
    @ResponseWrapper(localName = "getCurDateResponse", targetNamespace = "http://WebService/", className = "WS.GetCurDateResponse")
    @Action(input = "http://WebService/Dws/getCurDateRequest", output = "http://WebService/Dws/getCurDateResponse")
    public String getCurDate();

}
