
package WS;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.7-b01 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "DwsService", targetNamespace = "http://WebService/", wsdlLocation = "http://localhost:1111/Dws?wsdl")
public class DwsService
    extends Service
{

    private final static URL DWSSERVICE_WSDL_LOCATION;
    private final static WebServiceException DWSSERVICE_EXCEPTION;
    private final static QName DWSSERVICE_QNAME = new QName("http://WebService/", "DwsService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:1111/Dws?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        DWSSERVICE_WSDL_LOCATION = url;
        DWSSERVICE_EXCEPTION = e;
    }

    public DwsService() {
        super(__getWsdlLocation(), DWSSERVICE_QNAME);
    }

    public DwsService(WebServiceFeature... features) {
        super(__getWsdlLocation(), DWSSERVICE_QNAME, features);
    }

    public DwsService(URL wsdlLocation) {
        super(wsdlLocation, DWSSERVICE_QNAME);
    }

    public DwsService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, DWSSERVICE_QNAME, features);
    }

    public DwsService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DwsService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Dws
     */
    @WebEndpoint(name = "DwsPort")
    public Dws getDwsPort() {
        return super.getPort(new QName("http://WebService/", "DwsPort"), Dws.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Dws
     */
    @WebEndpoint(name = "DwsPort")
    public Dws getDwsPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://WebService/", "DwsPort"), Dws.class, features);
    }

    private static URL __getWsdlLocation() {
        if (DWSSERVICE_EXCEPTION!= null) {
            throw DWSSERVICE_EXCEPTION;
        }
        return DWSSERVICE_WSDL_LOCATION;
    }

}
